model_used = "scfoundation"
emb_type = 'gene-expression'  # universal/ gene-expression
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model_240614/models/scfoundation/models.ckpt'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model_240614/models/scfoundation/gene_vocab.json'
mode='v1'
highres=0 # 0
model_type='maeautobin'
bin_set='autobin_resolution_append' #autobin_resolution, bin_2, bin_3, no_bin
finetune_method='frozen' # [None,finetune, 'frozen', 'finetune_lr_1'])
accumulation_steps=5
key='gene'

# gears task params
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/perturbation/norman/scfoundation'
data_name = 'norman'
split = 'simulation'
seed=1
train_gene_set_size=0.75
batch_size=6
test_batch_size=6
device = 'cuda'
epochs = 15
lr = 1e-3
hidden_size=512
finetune = true
predict = false
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/perturbation/norman/scfoundation'
# wandb setting
weight_bias_track = true
proj_name = 'gears'
exp_name = 'norman_scf_e15_emb512'
