# path related
drug_smiles_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/223drugs_pubchem_smiles.txt'
drug_feature_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/GDSC/drug_graph_feat'
drug_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/GDSC/1.Drug_listMon Jun 24 09_00_55 2019.csv'
cell_line_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/Cell_lines_annotations_20181226.txt'
cancer_response_exp_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/GDSC_IC50.csv'
# expression / mutation / methylation
use_gexp = true
use_mut = false
use_methy = false
gene_expression_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_expression_561celllines_697genes_demap_features.csv'
genomic_mutation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_mutation_34673_demap_features.csv'
methylation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_methylation_561celllines_808genes_demap_features.csv'
# save
save_path = '/home/share/huadjyin/home/s_qiuping1/hanyuxuan/save'

# mamba path
model_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/best_model.pt'   ####### best_model  model_e1  model_e4
model_param_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/args.json'
vocab_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/vocab.json'

# deepcdr params
# mode
mode = 'train'
leave_drug_test = false
leave_drug = 0
# params
israndom = false  # randomlize X and A
lr = 1e-3
# hyparameters for GCN
unit_list = [256,256,256]
use_bn = true   # use batchnormalization for GCN
use_relu = true
use_GMP =true # use GlobalMaxPooling for GCN
max_atoms = 100

# mamba params
seed = 0
model_used = 'scmamba'
emb_type = 'cell'
device = 'cuda'
cell_emb_style = 'attn'  ####
do_pretrain = false
do_preprocess = false
input_style = "binned"    # normed_raw / log1p / binned
data_is_raw = false
include_zero_gene = false
hvg_number = false
dropout = 0.2
pad_token = '<pad>'
distributed = false
pad_value = -2
batch_size = 32
mask_ratio = 0
