output_dir='/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/demo/'

[CellEmbedding]
datasets=[
    'blood',
    'kidney',
    'liver',
]
scgpt=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scgpt/blood.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scgpt/kidney.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scgpt/liver.toml',
]
scbert=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scbert/blood.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scbert/kidney.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scbert/liver.toml',
]
geneformer=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/gf/blood.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/gf/kidney.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/gf/liver.toml',
]
scfoundation=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scf/blood.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scf/kidney.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scf/liver.toml',
]


[BatchEffect]
datasets=[
    'hpbmc',
    'hpancreas'
]
scgpt=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scgpt/hpbmc.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scgpt/hpancreas.toml',
]
scbert=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scbert/hpbmc.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scbert/hpancreas.toml',
]
geneformer=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/gf/hpbmc.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/gf/hpancreas.toml',
]
scfoundation=[
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scf/hpbmc.toml',
    '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/biollm/config/embeddings/cell_emb/scf/hpancreas.toml',
]