# data
# the param for the llm model, to init the foundation model.
model_used = "geneformer"
model_type = "CellClassifier"
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/models/geneformer'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/models/geneformer/gene_vocab.json'

# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/dataset/Zheng68K.h5ad'  # h5ad for the sc express matrix
output_dir = './'
device = '2'
quantile_cutoff = 0

# encoder
encoder_dims = 768
encoder_heads = 12
encoder_depth = 12

# the input data info, for the preocess step
hvg_number = 1200
data_is_raw = false
max_seq_len = 19264
use_g2v = false

# annotation task
cell_type_key = "celltype"



