# the param for the llm model, to init the foundation model.
model_used = "scbert"
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scBERT/ckpt/panglao_pretrain.pth'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene_vocab.json'
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/data/Immune_ALL_human.h5ad'  # h5ad for the sc express matrix
model_type = 'scbert'  # scgpt/scmamba/scbert
output_dir = './'
device = '1'
quantile_cutoff = 0
n_bins = 5
# the input data info, for the preocess step
hvg_number = 1200
data_is_raw = false
max_seq_len = 16096
use_g2v = true
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene2vec_16906.npy'
