# the param for the llm model, to init the foundation model.
model_used = "scgpt"
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/args.json'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/vocab.json'
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/data/Immune_ALL_human.h5ad'  # h5ad for the sc express matrix
model_type = 'scgpt'  # scgpt/scmamba/st_performer
output_dir = './'
device = '1'
quantile_cutoff = 0
# the input data info, for the preocess step
hvg_number = 1200
data_is_raw = false
scgpt_repo = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scGPT'
