model_used = "scmamba"
model_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/args.json'
vocab_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/vocab.json'
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/data/Immune_ALL_human.h5ad'  # h5ad for the sc express matrix
model_type = 'scmamba'  # scgpt/scmamba/st_performer
output_dir = './'
device = '1'
quantile_cutoff = 0
# the input data info, for the preocess step
hvg_number = 1200
data_is_raw = false
scmamba_repo = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scmamba'
pad_value = -2

