# data
# the param for the llm model, to init the foundation model.
model_used = "scfoundation"
model_file = '../../case/models/scfoundation/models.ckpt'
vocab_file = '../../case/models/scfoundation/gene_vocab.json'
key = "cell"

#embedding parameters
emb_type = "gene-expression"  # gene/gene-expression/cell
input_type = "singlecell" # "singlecell", "bulk"
tgthighres = "t4" #  the targeted high resolution (start with t) or the fold change of the high resolution (start with f), or the addtion (start with a) of the high resoultion. only valid for input_type=singlecell
pool_type = "all" # pooling type of cell embedding
batch_size = 8

# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/grn/Immune_ALL_human.h5ad'  # h5ad for the sc express matrix
output_dir = '../../case/result/zero-shot/'
device = 'cuda:0'
quantile_cutoff = 0

# encoder
encoder_dims = 128
encoder_heads = 12
encoder_depth = 12

# the input data info, for the preocess step
data_is_raw = false
max_seq_len = 19264
use_g2v = false
max_none_zero_num=5000
