# the param for the llm model, to init the foundation model.
model_used = "scgpt"
emb_type = 'gene' # gene/cell/gene-expression
model_file = '../../case/models/scgpt/best_model.pt'
model_param_file = '../../case/models/scgpt/args.json'
vocab_file = '../../case/models/scgpt/vocab.json'
# test h5ad, sc express matrix
output_dir = '../../case/result/zero-shot/'
pad_value = -2
mask_ratio = 0
device = 'cuda'
CLS = false  # celltype classification objective
ADV = false  # Adversarial training for batch correction
CCE = false  # Contrastive cell embedding objective
MVC = false  # Masked value prediction for cell embedding
ECS = false  # Elastic cell similarity objective

weight_bias_track = false
project_name = 'biollm'
exp_name = 'scgpt_gene_emb_gpu'