# data
# the param for the llm model, to init the foundation model.
model_used = "geneformer"
model_type = "Pretrained"
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_vocab.json'
gene_median_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_median_dict.json'
# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/tutorials/zero-shot/cabe6d98-2da8-4cd4-a8dc-66726eeb104a.h5ad'
output_dir = '../../case/result/zero-shot/'
device = 'cuda'
emb_type = 'cell'
batch_size = 8

# encoder
encoder_dims = 768
encoder_heads = 12
encoder_depth = 12




