# data
# the param for the llm model, to init the foundation model.
model_used = "geneformer"
model_type = "Pretrained"
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model_240614/models/geneformer'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model_240614/models/geneformer/gene_vocab.json'

# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/dataset/Zheng68K.h5ad'  # h5ad for the sc express matrix
output_dir = '../../case/result/zero-shot/'
device = 'cuda'
emb_type = 'gene'

# encoder
encoder_dims = 768
encoder_heads = 12
encoder_depth = 12
max_seq_len = 19264
use_g2v = false

# annotation task
cell_type_key = "celltype"

# wandb setting
weight_bias_track = false
project_name = 'biollm'
exp_name = 'geneformer_gene_emb_gpu'

