# the param for the llm model, to init the foundation model.
model_used = "scbert"
emb_type = 'cell' # gene/cell/gene-expression
model_file = '../../case/models/scbert/panglao_pretrain.pth'
vocab_file = '../../case/models/scbert/gene_vocab.json'
g2v_file = '../../case/models/scbert//gene2vec_16906.npy'
bin_num = 7
max_seq_len = 16907
use_g2v = true
embsize = 200
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/tutorials/zero-shot/cabe6d98-2da8-4cd4-a8dc-66726eeb104a.h5ad'
output_dir = '../../case/result/zero-shot/'
device = 'cuda'
distributed = false
batch_size = 8
cell_emb_type='mean' # cls/ mean/ sum
