model_used = "gene2vec"
g2v_genes = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene_name.txt'
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene2vec_16906.npy'
# gears args
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/norman_gene2vec'
data_name = 'norman'
split = 'simulation'
seed=52
train_gene_set_size=0.7
batch_size=32
test_batch_size=128
device = '0'
hidden_size = 200 # same with pretrain
epochs = 20
lr = 1e-3
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/norman_gene2vec'
use_pretrained = true
pretrain_freeze = false

