model_used = 'no'
emb_type = 'universal'
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/adamson'
data_name = 'adamson'
split = 'simulation'
seed=1
train_gene_set_size=0.75
batch_size=32
test_batch_size=128
device = 'cuda:2'
hidden_size = 64 # same with pretrain
epochs = 10
lr = 1e-3
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/adamson'
use_pretrained = false
pretrained_emb_size=512
pretrain_freeze = false
finetune=true

