model_used = 'scmamba' # scgpt/scbert/scmamba
emb_type = 'universal' # universal/gene-expression
# mamba args
model_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/args.json'
vocab_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/Mamba/gst_emb_mr5/vocab.json'
pad_value = -2
# input adata
data_is_raw = true
hvg_number = 5000

# gears args
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/adamson_scmamba'
data_name = 'adamson'
split = 'simulation'
seed=1
train_gene_set_size=0.75
batch_size=32
test_batch_size=128
device = 'cuda:2'
pretrained_emb_size = 512 # same with pretrain
hidden_size = 64 # same with pretrain
epochs = 10
lr = 1e-3
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/adamson_scmamba'
#result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/model/mamba'
use_pretrained = true
pretrain_freeze = false
finetune = true

