model_used = "scfoundation"
emb_type = 'gene-expression'  # universal/ gene-expression
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/models/scfoundation/models.ckpt'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/models/scfoundation/gene_vocab.json'
mode='v1'
highres=0 # 0
model_type='maeautobin'
bin_set='autobin_resolution_append' #autobin_resolution, bin_2, bin_3, no_bin
finetune_method='frozen' # [None,finetune, 'frozen', 'finetune_lr_1'])
accumulation_steps=1
key='gene'

#data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/repo/scFoundation/GEARS/data'
#data_name = 'pert'
#data_is_raw = true
#hvg_number=0
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/norman_scfoundation_source/adamson'
data_name = 'adamson'
split = 'simulation'
seed=1
train_gene_set_size=0.75
batch_size=32
test_batch_size=128
device = 'cuda'
epochs = 10
lr = 1e-3
hidden_size=512
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/gears_data/model/sc_foundation/adamson'

finetune = true
predict = false
