# the param for the task
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/pert/scgpt'  # h5ad for the sc express matrix
data_name = 'norman'
split = 'simulation'
seed = 1
emb_type = 'gene-expression'
device = 'cuda'
train_gene_set_size = 0.75
batch_size = 32
eval_batch_size = 32
finetune = true
epochs = 10
early_stop = 5
save_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/pert/scgpt'
predict = false
query = 'YIPF5+ctrl'
predict_sample_num = 300

model_used = 'scgpt'  # scgpt/scmamba/st_performer
#model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scGPT/tutorials/data/adamson/best_model.pt'
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/best_model.pt'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/vocab.json'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/model/scgpt_bc/args.json'
embsize = 512
nheads = 8
d_hid = 512
nlayers = 12
nlayers_cls = 3
dropout = 0.2
pad_token = '<pad>'
pad_value = 0
pert_pad_id = 2
MVC = false
MLM = true
cell_emb_style = 'cls'
mvc_decoder_style = 'inner product, detach'
use_fast_transformer = true

include_zero_gene = 'all' # all/batch-wise
max_seq_len = 1536
log_interval = 100
lr = 1e-4
schedule_interval = 1
