# the param for the task
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/pert/mamba/finetune'  # h5ad for the sc express matrix
data_name = 'norman'
split = 'simulation'
seed = 1
emb_type = 'gene-expression'
device = 'cuda'
train_gene_set_size = 0.75
batch_size = 32
eval_batch_size = 32
finetune = true
epochs = 15
early_stop = 5
save_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/pert/mamba/finetune/norman'
predict = true
query = 'YIPF5+ctrl'
predict_sample_num = 300
input_style = 'log1p'
do_pert = true

model_used = 'scmamba'  # scgpt/scmamba/st_performer
model_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/args.json'
vocab_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/vocab.json'
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/downstream_tasks/test/grn/data/Immune_ALL_human.h5ad'  # h5ad for the sc express matrix
distributed = false
do_pretrain = false
pad_token = '<pad>'
pad_value = 0
pert_pad_id = 2
MVC = false
MLM = true
cell_emb_style = 'cls'
mvc_decoder_style = 'inner product, detach'
use_fast_transformer = true
include_zero_gene = true
max_seq_len = 1536
log_interval = 100
lr = 1e-4
schedule_interval = 1
