# the param for the llm model, to init the foundation model.
model_used = "scbert"
emb_type = 'cell' # gene/cell/gene-expression
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/result/anno/scbert/hpancreas/best_model.pt'
vocab_file = '../../case/models/scbert/gene_vocab.json'
g2v_file = '../../case/models/scbert//gene2vec_16906.npy'
bin_num = 7
max_seq_len = 16907
use_g2v = true
embsize = 200
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/hpancreas/test.h5ad'
output_dir = '../../case/result/anno/cell_emb/scbert/'
device = 'cuda'
distributed = false
batch_size = 8
cell_emb_type='cls' # cls/ mean/ sum
