model_used = 'no'
emb_type = 'universal'
data_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/perturbation/norman'
data_name = 'norman'
split = 'simulation'
seed=1
train_gene_set_size=0.75
batch_size=32
test_batch_size=128
device = 'cuda:2'
hidden_size = 64 # same with pretrain
epochs = 10
lr = 1e-3
result_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/perturbation/norman/gears'
use_pretrained = false
finetune=true
