# data
# the param for the llm model, to init the foundation model.
model_used = "geneformer"
model_type = "Pretrained"
model_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_vocab.json'
gene_median_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_median_dict.json'

# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/grn/Immune_ALL_human.h5ad'
output_dir = '../../case/result/zero-shot/'
device = 'cuda:0'
emb_type = 'gene-expression'
batch_size = 8

# encoder
encoder_dims = 768
encoder_heads = 12
encoder_depth = 12




