# the param for the llm model, to init the foundation model.
model_used = "scbert"
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scBERT/ckpt/panglao_pretrain.pth'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene_vocab.json'
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/dataset/anno/Zheng68K.h5ad'  # h5ad for the sc express matrix
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/anno/Zheng68K'
device = 'cuda:1'
bin_num = 7
embsize = 200
distributed = false
batch_size = 6
finetune = true
predict = false
# the input data info, for the preocess step
do_preprocess = false
label_key = 'celltype'
max_seq_len = 16907
use_g2v = true
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene2vec_16906.npy'
lr = 0.0001
schedule_interval = 1
epochs=10
early_stop=5
