# the param for the llm model, to init the foundation model.
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert/panglao_pretrain.pth'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert/gene_vocab.json'
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert//gene2vec_16906.npy'
n_bins = 7
max_seq_len = 16907
use_g2v = true
embsize = 200

# task params
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/ms/c_data.h5ad'  # h5ad for the sc express matrix
test_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/ms/filtered_ms_adata.h5ad'  # h5ad for the sc express matrix
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/result/anno/scbert/ms/'
label_key = 'celltype'
var_key = 'gene_name'
batch_size = 8
GRADIENT_ACCUMULATION = 60
UNASSIGN_THRES = 0.0
# task params, user setting for the task
device = 'cuda:1'
distributed = false
finetune = true

## expert model train
model_used = "scbert"
lr = 0.001
epochs=20
early_stop=15
# wandb setting
weight_bias_track = true
project_name = 'biollm_annotation'
exp_name = 'scbert_ms'

