# the param for the llm model, to init the foundation model.
model_used = "scbert"
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/scBERT/ckpt/panglao_pretrain.pth'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene_vocab.json'
# model params, always not change
bin_num = 7
embsize = 200
max_seq_len = 16907
batch_size = 3
use_g2v = true
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/train_data/gene2vec/gene2vec_16906.npy'
GRADIENT_ACCUMULATION = 60
UNASSIGN_THRES = 0.0

# task params, user setting for the task
device = 'cuda:1'
distributed = true
finetune = true
predicted = false
# the input data info, for the preocess step
# test h5ad, sc express matrix
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/data/finetune/cell_annotation/scbert/liver.h5ad'
#input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/dataset/anno/Zheng68K.h5ad'
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/anno/liver'
do_preprocess = false
label_key = 'celltype'
# trainning params
lr = 0.001
epochs=50
early_stop=25

